# Generated by Django 3.2.7 on 2021-09-27 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TODO', '0002_auto_20210927_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TODO', to=settings.AUTH_USER_MODEL),
        ),
    ]
