# Generated by Django 3.2.7 on 2021-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_alter_project_link_to_repo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
